RP1_L00148202/Pages/AccessDenied.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RP1_L00148202.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RP1_L00148202/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RP1_L00148202.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

RP1_L00148202/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RP1_L00148202.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            return RedirectToPage("/Customer/Home/Index");
        }
        

        
    }
}

RP1_L00148202/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RP1_L00148202.Pages.PageViewModels;

namespace RP1_L00148202.Pages
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        [BindProperty]
        public Login Login { get; set; }
        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(Login.Email, Login.Password, Login.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    return RedirectToPage("/Index");
                }
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
            }
            return Page();
        }
    }
}

RP1_L00148202/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RP1_L00148202.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }

        public IActionResult OnPostNoLogout()
        {
            return RedirectToPage("Index");
        }
    }
}

RP1_L00148202/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RP1_L00148202.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

RP1_L00148202/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RP1.Models;
using RP1_L00148202.Pages.PageViewModels;

namespace RP1_L00148202.Pages
{
    [BindProperties]
    public class RegisterModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public Register Register { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

        public RegisterModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { FirstName = Register.FirstName,
                    LastName = Register.LastName,
                    UserName = Register.Email,
                    Email = Register.Email,
                    PhoneNumber = Register.PhoneNumber 
                };

                var result = await _userManager.CreateAsync(user, Register.Password);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, "Customer");
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToPage("/Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return Page();
        }
    }
}

RP1_L00148202/Pages/AccessDenied.cshtml
@page
@model RP1_L00148202.Pages.AccessDeniedModel
@{
}

RP1_L00148202/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RP1_L00148202/Pages/Login.cshtml
@page
@model RP1_L00148202.Pages.LoginModel
@{
}
<form method="post">
	<div class="border p-3 mt-4">
		<div asp-validation-summary="All" class="text-danger"></div>
		<div class="row pb-2">
			<h2 class="text-primary pl-3">
				Login
			</h2>
		</div>
		<div class="mb-3">
			<label asp-for="Login.Email"></label>
			<input asp-for="Login.Email" class="form-control" />
			<span asp-validation-for="Login.Email" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Login.Password"></label>
			<input asp-for="Login.Password" class="form-control" />
			<span asp-validation-for="Login.Password" class="text-danger"></span>
		</div>

		<button type="submit" class="btn btn-primary">Login</button>
		<a asp-page="Index" button type="submit" class="btn btn-outline-secondary">Home</a>
	</div>
</form>

@section Scripts {
	@{
		<partial name="_validationScriptsPartial" />
	}
}

RP1_L00148202/Pages/Logout.cshtml
@page
@model RP1_L00148202.Pages.LogoutModel
@{
    // Add any additional logic or messages here if needed
}

<form method="post">
    <div class="border p-3 mt-4">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="row pb-2"></div>
        <h2 class="text-primary p-lg-3">Logout</h2>
    </div>

    <div class="mb-3">
        <p> Are you sure you want to logout? </p>
        <p>
            <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
            <button class="btn btn-outline-secondary ml-5" asp-page-handler="NoLogout">No</button>    
        </p>
    </div>
</form>

RP1_L00148202/Pages/Register.cshtml
@page
@model RP1_L00148202.Pages.RegisterModel
@{
}
<form method="post">
	<div class="border p-3 mt-4">
		<div asp-validation-summary="All" class="text-danger"></div>
		<div class="row pb-2">
			<h2 class="text-primary pl-3">
				Register
			</h2>
		</div>
		<div class="mb-3">
			<label asp-for="Register.FirstName"></label>
			<input asp-for="Register.FirstName" class="form-control" />
			<span asp-validation-for="Register.FirstName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Register.LastName"></label>
			<input asp-for="Register.LastName" class="form-control" />
			<span asp-validation-for="Register.LastName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Register.PhoneNumber"></label>
			<input asp-for="Register.PhoneNumber" class="form-control" />
			<span asp-validation-for="Register.PhoneNumber" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Register.Email"></label>
			<input asp-for="Register.Email" class="form-control" />
			<span asp-validation-for="Register.Email" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Register.Password"></label>
			<input asp-for="Register.Password" class="form-control" />
			<span asp-validation-for="Register.Password" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Register.ConfirmPassword"></label>
			<input asp-for="Register.ConfirmPassword" class="form-control" />
			<span asp-validation-for="Register.ConfirmPassword" class="text-danger"></span>
		</div>

		<button type="submit" class="btn btn-primary">Register</button>
	</div>
</form>

@section Scripts {
	@{
		<partial name="_validationScriptsPartial" />
	}
}